#DXFIN
  #GENERAL
     DWGVersion = 2000
     Polyline = FALSE
     IgnoreAllUnvisibleLayers = FALSE
     ByLayer = FALSE
     CreateBlockAttributes = FALSE
     CreatePolylinesforPipes = FALSE
     IgnoreLayersOfSymbolComponents = FALSE
     UseTextInsteadOfMText = FALSE
     ExplodeReportTemplate = FALSE	
  #LNTYPES
    $DWG                   COMOS
     CONTINUOUS            1
     ACAD_ISO02W100        2
     ACAD_ISO03W100        2
     ACAD_ISO04W100        4
     ACAD_ISO05W100        5
     ACAD_ISO06W100        1
     ACAD_ISO07W100        9
     ACAD_ISO08W100        2
     ACAD_ISO10W100        3
  #COLORS
    $D-Color          C-R-Color  C-G-Color  C-B-Color  C-Linewidth
     7                0          0          0          13
     5                0          0          255        18
     2                255        255        0          25
     3                102        255        51         35
     1                204        0          0          50
     4                51         255        255        70
     6                255        0          255        100
  #LAYERS
    $D-Layer               C-Layer  C-Kennung
     1                     1        *
     2                     2        *
     3                     3        *
     4                     4        *
     5                     5        *
     6                     6        *
     7                     7        *
  #COMBINATIONS
    $D-COLOR          D-LNTYPE              D-LINEWIDTH  D-LAYER               C-R-COLOR  C-G-COLOR  C-B-COLOR  C-LNTYPE  C-LNWIDTH  C-LAYER  C-KENNUNG
