#DXFIN
  #GENERAL
     DWGVersion = 2000
     Polyline = FALSE
     IgnoreAllUnvisibleLayers = FALSE
     ByLayer = FALSE
     CreateBlockAttributes = FALSE
     CreatePolylinesforPipes = FALSE
     IgnoreLayersOfSymbolComponents = FALSE
     UseTextInsteadOfMText = FALSE
     ExplodeReportTemplate = FALSE
     OneBlockForCDevice = FALSE
     UseTemplateFile = FALSE
     ExportFrame = TRUE
     ExportDocHeader = TRUE
  #LNTYPES
    $DWG                   COMOS
  #COLORS
    $D-Color          C-R-Color  C-G-Color  C-B-Color  C-Linewidth
  #LAYERS
    $D-Layer               C-Layer  C-Kennung
     4                     4        *
     2                     2        *
     1                     1        *
     3                     3        *
  #COMBINATIONS
    $D-COLOR          D-LNTYPE              D-LINEWIDTH  D-LAYER               C-R-COLOR  C-G-COLOR  C-B-COLOR  C-LNTYPE  C-LNWIDTH  C-LAYER  C-KENNUNG
