#DXFIN
  #GENERAL
     IgnoreAllUnvisibleLayers = TRUE
  #LNTYPES
    $DWG              COMOS
  #COLORS
    $D-Color          C-R-Color C-G-Color  C-B-Color  C-Linewidth
  #LAYERS
    $D-Layer          C-Layer   C-Kennung
  #COMBINATIONS
    $D-COLOR          D-LNTYPE  D-LINEWIDTH  D-LAYER  C-R-COLOR C-G-COLOR  C-B-COLOR  C-LNTYPE  C-LNWIDTH  C-LAYER  C-KENNUNG
