;BOF: HARP.INI
;
; These placeholders are pre-defined for key <PrintToCommand>:
;
;    %PostScriptFullFileName% : The postscript file, which is created by printing 
;                               to the printer defined at <PrinterName>. 
;                               This value can be defined with the key <PrinterRedirection>.
;                               If this key is missing or is left blank, then
;                               the file will reside in the temporary folder as it
;                               is defined by windows with the filename "R2P<uniqueID>.PS".
;  %ConversionFullFileName%: The full filename of the converted file
;	                                  This value can be defined with the key <ConvertCommandOutputFullFileName>
;
;    %WindowsUser%            : The username, which windows reports as currently 
;                               logged in. This may differ from the user
;                               Comos® reports.
;
;    %TimeStamp%              : Timestamp with format of "yyyymmddhhnnss", which is
;                               set at the beginning of printing to postscript file
;
;    %ComosSystemUID%         : SystemUID of document that is being revised.
;
; This placeholder is pre-defined for keys <PrintToOutputFullFileName>, <PrinterRedirection>:
;
;    %WindowsUser%            : The username, which windows reports as the current 
;                               logged in account. This may differ from the user
;                               Comos® reports.
;
;    %TimeStamp%              : Timestamp with format of "yyyymmddhhnnss", which is
;                               set at the beginning of printing to postscript file
;
;    %ComosSystemUID%         : SystemUID of document that is being revised.
;
;These placeholders define the page layout:
; %LayoutOrientation%	:  This placeholder will be replaced by the comos document's actual orientation
;				   The value for Landscape will be defined in ConvertCommandLandscape
;				  The value for Portrait will be defined in ConvertCommandPortrait
;				  HARP does not support documents that switch orientations between single pages
; 
;
; These placeholders specify the revision file's paper size:
;% PaperSizeX%:	the paper width		: 
;			If this placeholder does not exist, setting layout explicitly will be omitted.
; %PaperSizeY%:	the paper height
;			If this placeholder does not exist, setting layout explicitly will be omitted.
;
; 
; ********************
; * IMPORTANT NOTICE *
; ********************
; All placeholder substitutions are case-sensitive !
;
;
; **********************
; * PostScript Printer *
; **********************
;  Port:
;  - "FILE:"
;  PostScript Options
;  - TrueTypeFontDownload Option: Outline
;
[Default]
PrinterName="Comos HARP"
RevisionExtension=.PDF
PrinterRedirection=C:\temp\ComosHARP\%ComosSystemUID%_%WindowsUser%_%TimeStamp%.PS
ConvertCommandOutputFullFileName=C:\temp\ComosHARP\%ComosSystemUID%_%WindowsUser%_%TimeStamp%.PDF
ConvertCommand=%GsCall% -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -dEmbedAllFonts=true -dAutoRotatePages=/None -sOutputFile=%ConversionFullFileName% -c "<< /Orientation %LayoutOrientation% >> setpagedevice" -f %PostScriptFullFileName%
ConvertCommandExecuteSynchronTimeOut=60
ConvertCommandRevisionSleeper=2
ConvertCommandDecimalDelimiter=.
ConvertCommandPrecision=2
ConvertCommandLandscape=3
ConvertCommandPortrait=0
[ConvertCommand Parameters]
;GsCall="C:\Program Files\gs\gs9.21\bin\gswin32c.exe" -q -dSAFER -dNOPAUSE -dBATCH
GsCall="C:\Program Files\gs\gs9.21\bin\gswin64c.exe" -q -dSAFER -dNOPAUSE -dBATCH
;EOF: HARP.INI

