#DXFIN
  #LNTYPES
        $AUTOCAD	LOGOCAD
	CONTINOUS	1
	ACAD_ISO02W100	2
	ACAD_ISO03W100	2
	ACAD_ISO04W100	4
	ACAD_ISO05W100	5
	ACAD_ISO06W100	1
	ACAD_ISO07W100	9
	ACAD_ISO08W100	2
  #COLORS
    $ACAD-Farbe    R-Farbe	G-Farbe	B-Farbe	LC-Breite
         7            0		0	0	   13
         5            0		0	255        18
         2            255	255	0	   25
         3            102	255	51         35
         1            204	0	0          50
         4            51	255	255        70
         6            255	0	255       100
  #LAYERS
    $ACAD-Layer   Comos-Layer Comos-Kennung 
         7            10       	  A		
         5            20       	  B		
         2            30       	  C		
         3            40       	  D		
         1            50       	  E		
         4            60       	  F		
         6            70       	  G		
