#DXFIN
  #LNTYPES
        $AUTOCAD	COMOS
	CONTINOUS	1
	ACAD_ISO02W100	2
	ACAD_ISO03W100	2
	ACAD_ISO04W100	4
	ACAD_ISO05W100	5
	ACAD_ISO06W100	1
	ACAD_ISO07W100	9
	ACAD_ISO08W100	2
	HIDDEN		2
	HIDDEN2		2
	DASHED		8
	DASHED2		2
	PHANTOM2	5
	PHANTOM		5
	BIG_DASH	2
  #COLORS
    $ACAD-Color       R-Color	G-Color	B-Color	   Comos-Width
         7            0		0	0	   1.0
         5            0		0	0          1.0
         2            0		0	0	   1.0
         3            0		0	0          1.0
         1            0		0	0          1.0
         4            0		0	0          1.0
         6            0		0	0	   1.0
  #LAYERS
    $ACAD-Layer   Comos-Layer Comos-Code 
         7            10       	  A		
         5            20       	  B		
         2            30       	  C		
         3            40       	  D		
         1            50       	  E		
         4            60       	  F		
         6            70       	  G		
